// Generated by CoffeeScript 1.7.1
(function() {
  var counter;

  counter = 0;

  exports.name = "ana";

  test("require a module at same folder with a required module", function() {
    counter++;
    if (counter === 2) {
      throw new Error("recursive require");
    }
    return ok(require("bob.js").name === "bob");
  });

}).call(this);
