// Generated by CoffeeScript 1.8.0
(function() {
  var context;

  context = new LeafRequire();

  descript("test leaf-require with config file", function() {
    it("load config should success", function(done) {
      return context.setConfig("./leaf-require.json", function(err) {
        return done(err);
      });
    });
    return it("load scripts should success", function(done) {
      return context.load(function() {
        return done();
      });
    });
  });

}).call(this);
