// Generated by CoffeeScript 1.7.1
(function() {
  var context;

  context = new LeafRequire({
    root: "./test/"
  });

  context.use("a.js", "b.js", "c.js", "main.js", "sub/subA.js", "sub/subB.js", "rootA.js");

  context.load(function() {
    console.log("inited");
    context.require("main.js");
    return context.require("sub/subA.js");
  });

}).call(this);
