// Generated by CoffeeScript 1.6.3
(function() {
  var context;

  context = new LeafRequire();

  context.setRoot("./");

  context.use("a.js", "b.js", "c.js", "main.js");

  context.load(function() {
    return context.require("main.js");
  });

}).call(this);
