// Generated by CoffeeScript 1.8.0
(function() {
  exports.name = "madoka";

  test("require a module from parent folder", function() {
    return ok(require("../root.js").name === "root");
  });

}).call(this);
