// Generated by CoffeeScript 1.8.0
(function() {
  exports.name = "qubi";

  test("require a module without .js ../sub/module", function() {
    return ok(require("../sub/madoka").name === "madoka");
  });

}).call(this);
