// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  module.exports = function(grunt) {
    grunt.initConfig({
      connect: {
        server: {
          options: {
            port: 3000,
            base: ".",
            hostname: "*"
          }
        }
      },
      watch: {
        all: {
          options: {
            livereload: true
          },
          files: ['test/index.html', 'leafRequire.js']
        }
      }
    });
    grunt.loadNpmTasks('grunt-contrib-connect');
    grunt.loadNpmTasks('grunt-contrib-watch');
    return grunt.registerTask('develop', ['connect', 'watch']);
  };

}).call(this);
