// Generated by CoffeeScript 1.8.0
(function() {
  var counter;

  counter = 0;

  exports.name = "ana";

  it("require a module at same folder with a required module", function(done) {
    counter++;
    if (counter === 2) {
      throw new Error("recursive require");
    }
    console.assert(require("bob.js").name === "bob");
    return done();
  });

}).call(this);
