// Generated by CoffeeScript 1.8.0
(function() {
  exports.name = "bob";

  it("require a module who required me", function(done) {
    console.assert(require("ana.js").name === "ana");
    return done();
  });

}).call(this);
