// Generated by CoffeeScript 1.7.1
(function() {
  exports.name = "bob";

  test("require a module who required me", function() {
    return ok(require("ana.js").name === "ana");
  });

}).call(this);
