// Generated by CoffeeScript 1.8.0
(function() {
  window.mainLoaded = true;

  it("require a module from the same folder", function(done) {
    console.assert(require("ana.js").name === "ana");
    return done();
  });

}).call(this);
