// Generated by CoffeeScript 1.8.0
(function() {
  exports.name = "root";

  test("require a module from a sub folder", function() {
    return ok(require("sub/qubi.js").name === "qubi");
  });

}).call(this);
