// Generated by CoffeeScript 1.8.0
(function() {
  var loader;

  loader = new LeafRequire.BestPractice({
    localStoragePrefix: "SybilLeafRequire",
    config: "./require.json",
    showDebugInfo: true,
    entry: "main"
  });

  loader.run();

}).call(this);
