// Generated by CoffeeScript 1.10.0
(function() {
  var bp, config, ref;

  config = (ref = window.location.hash.toString()) != null ? ref.replace("#", "") : void 0;

  bp = new LeafRequire.BestPractice({
    config: config,
    debug: true
  });

  bp.run();

  window.GlobalContext = bp.context;

}).call(this);
