// Generated by CoffeeScript 1.10.0
(function() {
  var common;

  common = require("./common");

  self.addEventListener("message", (function(_this) {
    return function(e) {
      if (e.data === common.getTestData()) {
        return self.postMessage(common.getTestData());
      } else {
        return console.error("invalid message");
      }
    };
  })(this));

  self.postMessage("ready");

}).call(this);
